/*
================================================================================
  DAILY_DATA_REFRESH Task
  
  Refreshes EDGAR_FILINGS and PUBLIC_TRANSCRIPTS tables from Snowflake Marketplace
  and triggers incremental updates to Cortex Search Services.
  
  Schedule: Daily at 6:00 AM UTC
  Warehouse: HOLLY_WH
================================================================================
*/

CREATE OR REPLACE TASK COLM_DB.STRUCTURED.DAILY_DATA_REFRESH
  WAREHOUSE = HOLLY_WH
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Daily refresh of EDGAR_FILINGS and PUBLIC_TRANSCRIPTS tables at 6:00 AM UTC'
AS
BEGIN
  MERGE INTO COLM_DB.SEMI_STRUCTURED.EDGAR_FILINGS AS target
  USING (
    SELECT 
      COMPANY_NAME,
      FORM_TYPE AS ANNOUNCEMENT_TYPE,
      FILED_DATE::DATE AS FILED_DATE,
      FISCAL_PERIOD,
      FISCAL_YEAR::FLOAT AS FISCAL_YEAR,
      ITEM_NUMBER,
      ITEM_TITLE,
      PLAINTEXT_CONTENT AS ANNOUNCEMENT_TEXT
    FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.SEC_CORPORATE_REPORT_ITEM_ATTRIBUTES
    WHERE PLAINTEXT_CONTENT IS NOT NULL
  ) AS source
  ON target.COMPANY_NAME = source.COMPANY_NAME 
     AND target.FILED_DATE = source.FILED_DATE 
     AND target.ITEM_NUMBER = source.ITEM_NUMBER
  WHEN NOT MATCHED THEN
    INSERT (COMPANY_NAME, ANNOUNCEMENT_TYPE, FILED_DATE, FISCAL_PERIOD, FISCAL_YEAR, ITEM_NUMBER, ITEM_TITLE, ANNOUNCEMENT_TEXT)
    VALUES (source.COMPANY_NAME, source.ANNOUNCEMENT_TYPE, source.FILED_DATE, source.FISCAL_PERIOD, source.FISCAL_YEAR, source.ITEM_NUMBER, source.ITEM_TITLE, source.ANNOUNCEMENT_TEXT);

  MERGE INTO COLM_DB.UNSTRUCTURED.PUBLIC_TRANSCRIPTS AS target
  USING (
    SELECT 
      COMPANY_ID,
      CIK,
      COMPANY_NAME,
      PRIMARY_TICKER,
      FISCAL_PERIOD,
      FISCAL_YEAR,
      EVENT_TYPE,
      TRANSCRIPT,
      EVENT_TIMESTAMP
    FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.COMPANY_EVENT_TRANSCRIPT_ATTRIBUTES
    WHERE TRANSCRIPT IS NOT NULL
  ) AS source
  ON target.COMPANY_ID = source.COMPANY_ID 
     AND target.EVENT_TIMESTAMP = source.EVENT_TIMESTAMP
     AND target.FISCAL_PERIOD = source.FISCAL_PERIOD
     AND target.FISCAL_YEAR = source.FISCAL_YEAR
  WHEN NOT MATCHED THEN
    INSERT (COMPANY_ID, CIK, COMPANY_NAME, PRIMARY_TICKER, FISCAL_PERIOD, FISCAL_YEAR, EVENT_TYPE, TRANSCRIPT, EVENT_TIMESTAMP)
    VALUES (source.COMPANY_ID, source.CIK, source.COMPANY_NAME, source.PRIMARY_TICKER, source.FISCAL_PERIOD, source.FISCAL_YEAR, source.EVENT_TYPE, source.TRANSCRIPT, source.EVENT_TIMESTAMP);
END;

ALTER TASK COLM_DB.STRUCTURED.DAILY_DATA_REFRESH RESUME;
