create or replace cortex search service EDGAR_FILINGS
	ON COMPANY_NAME
	attributes COMPANY_NAME,ANNOUNCEMENT_TYPE,FILED_DATE,FISCAL_PERIOD,FISCAL_YEAR,ITEM_NUMBER,ITEM_TITLE
	warehouse='SMALL_WH'
	target_lag='1 day'
	EMBEDDING_MODEL='snowflake-arctic-embed-l-v2.0'
	refresh_mode=INCREMENTAL
	as (
	SELECT
		COMPANY_NAME,
		ANNOUNCEMENT_TYPE,
		FILED_DATE,
		FISCAL_PERIOD,
		FISCAL_YEAR,
		ITEM_NUMBER,
		ITEM_TITLE,
		ANNOUNCEMENT_TEXT
	FROM COLM_DB.SEMI_STRUCTURED.EDGAR_FILINGS
);
