create or replace cortex search service TRANSCRIPTS
	ON TITLE
	attributes TITLE,AGENDA,CONTENT_TYPE,TARGET_COMPANIES,STARTS_AT,TRANSCRIPT_URL,RELEVANT_COMPANIES
	warehouse='SMALL_WH'
	target_lag='1 day'
	EMBEDDING_MODEL='snowflake-arctic-embed-l-v2.0'
	refresh_mode=INCREMENTAL
	as (
	SELECT
		TITLE,
		AGENDA,
		CONTENT_TYPE,
		TARGET_COMPANIES,
		STARTS_AT,
		TRANSCRIPT_URL,
		RELEVANT_COMPANIES,
		TRANSCRIPT
	FROM COLM_DB.UNSTRUCTURED.TB_TRANSCRIPTS
);
