CREATE OR REPLACE CORTEX SEARCH SERVICE COLM_DB.UNSTRUCTURED.TB_TRANSCRIPTS
    ON TITLE
    ATTRIBUTES TITLE, AGENDA, CONTENT_TYPE, TARGET_COMPANIES, STARTS_AT, TRANSCRIPT_URL, RELEVANT_COMPANIES
    WAREHOUSE = 'SMALL_WH'
    TARGET_LAG = '1 day'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
    SELECT
        TITLE,
        AGENDA,
        CONTENT_TYPE,
        TARGET_COMPANIES,
        STARTS_AT,
        TRANSCRIPT_URL,
        RELEVANT_COMPANIES,
        TRANSCRIPT
    FROM COLM_DB.UNSTRUCTURED.TB_TRANSCRIPTS
);
